### ISSUE TITLE
01. Documentação de Contexto

### ISSUE THREAD

**Issue by pauloroncarati** [ICEI-PUC-Minas-PMV-ADS/gestao-locacoes#34]
Faltam:
- [x] [Problema](https://github.com/ICEI-PUC-Minas-PMV-ADS/gestao-locacoes/blob/main/docs/documentacao-de-contexto.md#problema)
- [x] [Objetivos](https://github.com/ICEI-PUC-Minas-PMV-ADS/gestao-locacoes/blob/main/docs/documentacao-de-contexto.md#objetivos)
- [x] [Justificativa](https://github.com/ICEI-PUC-Minas-PMV-ADS/gestao-locacoes/blob/main/docs/documentacao-de-contexto.md#justificativa)

**Comment by hashtagluan** [comment]
feitos
