### ISSUE TITLE
05 - Arquitetura da Solução

### ISSUE THREAD

**Issue by pauloroncarati** [ICEI-PUC-Minas-PMV-ADS/gestao-locacoes#51]

**Comment by hashtagluan** [comment]
criado o Modelo Entidade Relacionamento (Projeto Conceitual) |

**Comment by pauloroncarati** [comment]
Fala pessoal, nesse doc está faltando os diagramas em:

- [ ] [Modelo ER (Projeto Conceitual)](https://github.com/ICEI-PUC-Minas-PMV-ADS/gestao-locacoes/blob/main/docs/05-arquitetura-da-solucao.md#modelo-er-projeto-conceitual)
- [ ] [Projeto da Base de Dados](https://github.com/ICEI-PUC-Minas-PMV-ADS/gestao-locacoes/blob/main/docs/05-arquitetura-da-solucao.md#projeto-da-base-de-dados)
